import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavigationBar from '../component/layOut/Header';
import Footer from '@/component/layOut/Footer';
import localFont from 'next/font/local';

const sans = localFont({
  src: '../public/fonts/DMSans-VariableFont_opsz,wght.ttf',
  variable: '--font-DmSans',
  weight: '100 900',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'
        />
      </head>
      <body className={`${sans.variable} antialiased`}>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
