import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "../component/layOut/Header";
import Footer from "@/component/layOut/Footer";
import localFont from "next/font/local";
import fetchProductMenu from "@/utills/fetchProductMenu";

const sans = localFont({
  src: '../public/fonts/DMSans-VariableFont_opsz,wght.ttf',
  variable: '--font-DmSans',
  weight: '100 900',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const productMenu = await fetchProductMenu();
  const navItems = [
    { label: "Home", href: "/", active: true },
    { label: "About Us", href: "/about-us" },
    { label: "Facility", href: "/facility" },
    { label: "Products", href: "/product" },
    { label: "Our Divisions", href: "/our-divisions" },
    { label: "New Launches", href: "/new-launches" },
    { label: "Gallery", href: "/gallery" },
  ];
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'
        />
      </head>
      <body className={`${sans.variable} antialiased`}>
        <NavigationBar navBar={navItems} productMenu={productMenu} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
